### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by gayat19** [sukesh-n/Capstone-Project#2]
All good. I just have one question. If a hotel owner is deleted what happens to the hotel, rooms added by him? also what will happen to the booking done for those rooms?

**Comment by sukesh-n** [comment]
In the event of a deletion/change in hotel ownership or management, future bookings may be temporarily suspended for evaluation. Existing bookings are specially maintained unless unforeseen circumstances, such as temporary/permanent closures of hotels. Payments made successfully through the website are typically credited after the guest checks out from the hotel. If a guest cancels before checking out or if the hotel owner is removed, any respective amounts are promptly refunded to the guest.

**Comment by gayat19** [comment]
Okay then . Please proceed
